### ISSUE TITLE
HTML tag spacing strange

### ISSUE THREAD

**Issue by idealerror** [archtechx/laravel-seo#19]
Hey team,

How come when using the `<x-seo::meta />` tag, it inputs the HTML all strange? It adds tabs randomly, adds new lines randomly, and joins some things together on the same line.  Why not just input everything one line after eachother?

Controller Code:
```
 seo()
            ->title('News & Updates - MySite')
            ->description('Find out the latest')
            ->site('MySite')
            ->twitter();
```

Actual HTML output:
```
<title>News & Updates - MySite</title>  
        <meta property="og:title" content="News & Updates - MySite" />
 
<meta property="og:description" content="Find out the latest" />
<meta name="description" content="Find out the latest" />
 
<meta property="og:type" content="website" />

<meta property="og:site_name" content="MySite">
  
    <meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="MySite">  <meta name="twitter:title" content="News & Updates - MySite">  <meta name="twitter:description" content="Find out the latest">
```

**Comment by stancl** [comment]
This is pretty common for Blade. When you have `@if` conditions with indented content (see our Blade views), or when you indent components, the output will have indentation like that.

It's a very usual thing in Laravel. I see why it can be surprising at first, but it's simply the way Laravel works and there are no real issues stemming from this.

**Comment by nicolaibaaring** [comment]
It is actually possible to achieve this on a package level. But it requires that the formatting is built into the Blade files (and thus not altered by any kind of linter/formatter). I've tested in Chrome and Firefox.

Let me know if you are interested in a PR to fix this.
