### ISSUE TITLE
[FEATURE] Favicon support

### ISSUE THREAD

**Issue by heychazza** [archtechx/laravel-seo#3]
It would be awesome if this could be added, I know its not directly SEO but it touches with images etc.

**Comment by stancl** [comment]
It's beyond the scope of the package, but you can use the <head> control by using custom tags, like `seo()->tag('<link ... />')`.

**Comment by heychazza** [comment]
> It's beyond the scope of the package, but you can use the control by using custom tags, like `seo()->tag('<link ... />')`.

Thank you, is it possible to be able to set a default for it, and override where needed?

**Comment by stancl** [comment]
Not at the moment. If more people need it I'll refactor the codebase to allow for these things as well

**Comment by heychazza** [comment]
> Not at the moment. If more people need it I'll refactor the codebase to allow for these things as well

Please!! Even if we can assign a tag to an ID, and then set that id or something later

**Comment by stancl** [comment]
Alright, found a simple way to add this. You can use `rawTag('foo', '<my tag>')` and later `rawTag('foo', '<a different tag>;)`

**Comment by heychazza** [comment]
> Alright, found a simple way to add this. You can use `rawTag('foo', '<my tag>')` and later `rawTag('foo', '<a different tag>;)`

Absolute god send!!!! Thank you
