### ISSUE TITLE
Edit everything myself

### ISSUE THREAD

**Issue by hako2008** [archtechx/laravel-seo#31]
If i will edit everything myself why i would use a package for that????
this is all the tags you need, i guess there is no one can't fill them the correct way:

```
<meta name="description" content=""/>
<meta name="author" content="" />

<meta name="robots" content="index, follow" />
<meta property="og:title" content="" />
<meta property="og:description" content="" />
<meta property="og:type" content="og:product" />
<meta property="og:url" content="" />
<meta property="og:image" content="" />
<meta property="product:plural_title"      content="" />
<meta property="product:price:amount"      content=""/>
<meta property="product:price:currency"    content="USD"/>
```
for more social tags : [ogp.me](https://ogp.me/)

**Comment by stancl** [comment]
The point of the package is that it provides a globally accessible layer for storing the data that goes into these tags during the request.

This means that you can fill the data in one part (or several parts) of the application, and then simply use `<x-seo::meta />` in your Blade template to render tags for all of the bits of data you filled throughout the request lifecycle.
