### ISSUE TITLE
Raw tags cannot be overridden

### ISSUE THREAD

**Issue by heychazza** [archtechx/laravel-seo#6]
When using raw tags (with the keys), it only adds additional HTML entries into the header, I know the concept behind it is to override as we spoke about previously. I personally use this for favicons, where I change it for viewing pages with user uploaded avatars.

When diving further, your tests (as found https://github.com/archtechx/laravel-seo/blob/master/tests/Pest/ManagerTest.php#L102) seem to reference the wrong value. Shouldn't this be checking for the newer entry, rather than the original abc?

**Comment by stancl** [comment]
Fixed in latest commit, thanks
