### ISSUE TITLE
Multifunctional methods

### ISSUE THREAD

**Issue by szepeviktor** [archtechx/laravel-seo#8]
Hello! While resolving all ignored PHPStan errors I've bumped into methods like `SEOManager::meta`. Or the `seo` function.

Please consider using 1 method for 1 thing.

> Get or set metadata.

The "S" in [SOLID](https://en.wikipedia.org/wiki/SOLID).

**Comment by stancl** [comment]
Hey. Thanks for the feedback, but here we specifically want the nice `seo()->title()` syntax, without `getTitle()` or `setTitle()`. Those aren't in line with our values as far as code style goes. We don't prioritize following design principles at the cost of expressive code.
